// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/go-webauthn/webauthn/webauthn"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
	"long/internal/types"
)

type DeletionStatus string

const (
	DeletionStatusActive   DeletionStatus = "active"
	DeletionStatusApproved DeletionStatus = "approved"
	DeletionStatusRejected DeletionStatus = "rejected"
	DeletionStatusRevoked  DeletionStatus = "revoked"
)

func (e *DeletionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DeletionStatus(s)
	case string:
		*e = DeletionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DeletionStatus: %T", src)
	}
	return nil
}

type NullDeletionStatus struct {
	DeletionStatus DeletionStatus `json:"deletionStatus"`
	Valid          bool           `json:"valid"` // Valid is true if DeletionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDeletionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DeletionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DeletionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDeletionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DeletionStatus), nil
}

type Rating string

const (
	RatingNone     Rating = "none"
	RatingModerate Rating = "moderate"
	RatingViolent  Rating = "violent"
)

func (e *Rating) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Rating(s)
	case string:
		*e = Rating(s)
	default:
		return fmt.Errorf("unsupported scan type for Rating: %T", src)
	}
	return nil
}

type NullRating struct {
	Rating Rating `json:"rating"`
	Valid  bool   `json:"valid"` // Valid is true if Rating is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRating) Scan(value interface{}) error {
	if value == nil {
		ns.Rating, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Rating.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRating) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Rating), nil
}

type UploadStatus string

const (
	UploadStatusActive    UploadStatus = "active"
	UploadStatusExpired   UploadStatus = "expired"
	UploadStatusCompleted UploadStatus = "completed"
)

func (e *UploadStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UploadStatus(s)
	case string:
		*e = UploadStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UploadStatus: %T", src)
	}
	return nil
}

type NullUploadStatus struct {
	UploadStatus UploadStatus `json:"uploadStatus"`
	Valid        bool         `json:"valid"` // Valid is true if UploadStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUploadStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UploadStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UploadStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUploadStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UploadStatus), nil
}

type Appkey struct {
	ID              int64            `json:"id"`
	Label           string           `json:"label"`
	CreatedAt       pgtype.Timestamp `json:"createdAt"`
	UserID          int64            `json:"userId"`
	Permission      int64            `json:"permission"`
	LastActivatedAt pgtype.Timestamp `json:"lastActivatedAt"`
	Key             string           `json:"key"`
}

type Deletion struct {
	ID          int64            `json:"id"`
	CreatedAt   pgtype.Timestamp `json:"createdAt"`
	ProcessedAt pgtype.Timestamp `json:"processedAt"`
	ImageID     int64            `json:"imageId"`
	Reason      string           `json:"reason"`
	Status      DeletionStatus   `json:"status"`
}

type Image struct {
	ID               int64            `json:"id"`
	CreatedAt        pgtype.Timestamp `json:"createdAt"`
	UpdatedAt        pgtype.Timestamp `json:"updatedAt"`
	DeletedAt        pgtype.Timestamp `json:"deletedAt"`
	UserID           int64            `json:"userId"`
	ImageKey         string           `json:"imageKey"`
	ImageUrl         string           `json:"imageUrl"`
	ImageHash        pgtype.Text      `json:"imageHash"`
	ActiveDeletionID pgtype.Int8      `json:"activeDeletionId"`
	CurrentVersionID pgtype.Int8      `json:"currentVersionId"`
	Embedding        pgvector.Vector  `json:"embedding"`
}

type ServerConfig struct {
	Name  string `json:"name"`
	Value []byte `json:"value"`
}

type Tag struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type UploadSession struct {
	ID          int64            `json:"id"`
	CreatedAt   pgtype.Timestamp `json:"createdAt"`
	CompletedAt pgtype.Timestamp `json:"completedAt"`
	UserID      int64            `json:"userId"`
	Key         string           `json:"key"`
	Status      UploadStatus     `json:"status"`
}

type User struct {
	ID           int64            `json:"id"`
	CreatedAt    pgtype.Timestamp `json:"createdAt"`
	Email        string           `json:"email"`
	Username     string           `json:"username"`
	Permission   int64            `json:"permission"`
	PasswordHash []byte           `json:"passwordHash"`
	Handle       []byte           `json:"handle"`
	Preference   types.Preference `json:"preference"`
}

type UserFavorite struct {
	UserID      int64            `json:"userId"`
	ImageID     int64            `json:"imageId"`
	Shortcut    pgtype.Text      `json:"shortcut"`
	FavoritedAt pgtype.Timestamp `json:"favoritedAt"`
}

type UserIdentifier struct {
	ID        int64            `json:"id"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
	Username  string           `json:"username"`
}

type Version struct {
	ID        int64            `json:"id"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
	ImageID   int64            `json:"imageId"`
	Version   int32            `json:"version"`
	Text      string           `json:"text"`
	Rating    Rating           `json:"rating"`
	UserID    int64            `json:"userId"`
}

type VersionTag struct {
	VersionID int64 `json:"versionId"`
	TagID     int64 `json:"tagId"`
}

type WebauthnPasskey struct {
	ID         []byte           `json:"id"`
	Name       string           `json:"name"`
	UserID     int64            `json:"userId"`
	PublicKey  []byte           `json:"publicKey"`
	SignCount  int64            `json:"signCount"`
	Transports []string         `json:"transports"`
	Flags      int16            `json:"flags"`
	CreatedAt  pgtype.Timestamp `json:"createdAt"`
	Aaguid     pgtype.UUID      `json:"aaguid"`
}

type WebauthnSession struct {
	ID        string               `json:"id"`
	CreatedAt pgtype.Timestamp     `json:"createdAt"`
	Data      webauthn.SessionData `json:"data"`
}

type Webhook struct {
	ID                 int64            `json:"id"`
	CreatedAt          pgtype.Timestamp `json:"createdAt"`
	UserID             int64            `json:"userId"`
	Label              string           `json:"label"`
	Endpoint           string           `json:"endpoint"`
	Event              int32            `json:"event"`
	Secret             string           `json:"secret"`
	LastActivatedAt    pgtype.Timestamp `json:"lastActivatedAt"`
	LastResponseStatus pgtype.Int4      `json:"lastResponseStatus"`
}
