// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlc

import (
	"context"

	"github.com/go-webauthn/webauthn/webauthn"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
	"long/internal/types"
)

const addFavorite = `-- name: AddFavorite :exec
INSERT INTO user_favorite(user_id, image_id, shortcut)
VALUES ($1, $2, $3)
`

type AddFavoriteParams struct {
	UserID   int64       `json:"userId"`
	ImageID  int64       `json:"imageId"`
	Shortcut pgtype.Text `json:"shortcut"`
}

func (q *Queries) AddFavorite(ctx context.Context, arg AddFavoriteParams) error {
	_, err := q.db.Exec(ctx, addFavorite, arg.UserID, arg.ImageID, arg.Shortcut)
	return err
}

const completeUploadSession = `-- name: CompleteUploadSession :one
UPDATE public.upload_session
SET "completed_at" = NOW(), "status" = 'completed'
WHERE "id" = $1
    AND "user_id" = $2
    AND "status" = 'active'
RETURNING id, created_at, completed_at, user_id, key, status
`

type CompleteUploadSessionParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"userId"`
}

func (q *Queries) CompleteUploadSession(ctx context.Context, arg CompleteUploadSessionParams) (UploadSession, error) {
	row := q.db.QueryRow(ctx, completeUploadSession, arg.ID, arg.UserID)
	var i UploadSession
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.UserID,
		&i.Key,
		&i.Status,
	)
	return i, err
}

const countFavoriteImages = `-- name: CountFavoriteImages :one
SELECT COUNT(*)
FROM user_favorite
WHERE user_id = $1
`

func (q *Queries) CountFavoriteImages(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countFavoriteImages, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countImages = `-- name: CountImages :one
SELECT COUNT(*) FROM public.image
WHERE deleted_at IS NULL
`

func (q *Queries) CountImages(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countImages)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countImagesByUser = `-- name: CountImagesByUser :one
SELECT COUNT(*) FROM image
WHERE "user_id" = $1 AND "deleted_at" IS NULL
`

func (q *Queries) CountImagesByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countImagesByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTagsWithPrefix = `-- name: CountTagsWithPrefix :one
SELECT COUNT(*) FROM public.tag
WHERE name LIKE CONCAT($1, '%')
`

func (q *Queries) CountTagsWithPrefix(ctx context.Context, text interface{}) (int64, error) {
	row := q.db.QueryRow(ctx, countTagsWithPrefix, text)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countVersionsByUser = `-- name: CountVersionsByUser :one
SELECT COUNT(*) FROM version
WHERE user_id = $1
`

func (q *Queries) CountVersionsByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countVersionsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAppKey = `-- name: CreateAppKey :one
INSERT INTO appkey(user_id, permission, label, key)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateAppKeyParams struct {
	UserID     int64  `json:"userId"`
	Permission int64  `json:"permission"`
	Label      string `json:"label"`
	Key        string `json:"key"`
}

func (q *Queries) CreateAppKey(ctx context.Context, arg CreateAppKeyParams) (int64, error) {
	row := q.db.QueryRow(ctx, createAppKey,
		arg.UserID,
		arg.Permission,
		arg.Label,
		arg.Key,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createCredential = `-- name: CreateCredential :exec
INSERT INTO webauthn_passkey(id, user_id, public_key, sign_count, transports, aaguid, flags)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateCredentialParams struct {
	ID         []byte      `json:"id"`
	UserID     int64       `json:"userId"`
	PublicKey  []byte      `json:"publicKey"`
	SignCount  int64       `json:"signCount"`
	Transports []string    `json:"transports"`
	Aaguid     pgtype.UUID `json:"aaguid"`
	Flags      int16       `json:"flags"`
}

func (q *Queries) CreateCredential(ctx context.Context, arg CreateCredentialParams) error {
	_, err := q.db.Exec(ctx, createCredential,
		arg.ID,
		arg.UserID,
		arg.PublicKey,
		arg.SignCount,
		arg.Transports,
		arg.Aaguid,
		arg.Flags,
	)
	return err
}

const createImage = `-- name: CreateImage :one
INSERT INTO image(image_key, image_url, user_id)
VALUES ($1, $2, $3)
RETURNING id
`

type CreateImageParams struct {
	ImageKey string `json:"imageKey"`
	ImageUrl string `json:"imageUrl"`
	UserID   int64  `json:"userId"`
}

func (q *Queries) CreateImage(ctx context.Context, arg CreateImageParams) (int64, error) {
	row := q.db.QueryRow(ctx, createImage, arg.ImageKey, arg.ImageUrl, arg.UserID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createNewVersion = `-- name: CreateNewVersion :exec
WITH new_version AS (
    INSERT INTO version("text", "rating", "user_id", "image_id", "version")
    SELECT $1, $2, $3, image.id, version.version + 1
    FROM image
    JOIN version ON image.current_version_id = version.id
    WHERE image.id = $5
    RETURNING id
),
new_image AS (
    UPDATE image
    SET current_version_id = nv.id
    FROM new_version nv
    WHERE image.id = $5
)
INSERT INTO version_tag (version_id, tag_id)
SELECT nv.id, t.id
FROM new_version nv
JOIN tag t ON t.name = ANY($4::TEXT[])
`

type CreateNewVersionParams struct {
	Text     string   `json:"text"`
	Rating   Rating   `json:"rating"`
	UserID   int64    `json:"userId"`
	TagNames []string `json:"tagNames"`
	ImageID  int64    `json:"imageId"`
}

func (q *Queries) CreateNewVersion(ctx context.Context, arg CreateNewVersionParams) error {
	_, err := q.db.Exec(ctx, createNewVersion,
		arg.Text,
		arg.Rating,
		arg.UserID,
		arg.TagNames,
		arg.ImageID,
	)
	return err
}

const createTags = `-- name: CreateTags :exec
INSERT INTO tag ("name")
SELECT name
FROM UNNEST($1::TEXT[]) AS n("name")
ON CONFLICT ("name") DO NOTHING
`

func (q *Queries) CreateTags(ctx context.Context, tagNames []string) error {
	_, err := q.db.Exec(ctx, createTags, tagNames)
	return err
}

const createUploadSession = `-- name: CreateUploadSession :one
INSERT INTO public.upload_session (
    "user_id", "key"
) VALUES (
    $1, $2
) RETURNING id, created_at, completed_at, user_id, key, status
`

type CreateUploadSessionParams struct {
	UserID int64  `json:"userId"`
	Key    string `json:"key"`
}

func (q *Queries) CreateUploadSession(ctx context.Context, arg CreateUploadSessionParams) (UploadSession, error) {
	row := q.db.QueryRow(ctx, createUploadSession, arg.UserID, arg.Key)
	var i UploadSession
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.UserID,
		&i.Key,
		&i.Status,
	)
	return i, err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO public.user (
    "email", "username", "permission", "password_hash"
) VALUES (
    $1, $2, $3, $4
)
`

type CreateUserParams struct {
	Email        string `json:"email"`
	Username     string `json:"username"`
	Permission   int64  `json:"permission"`
	PasswordHash []byte `json:"passwordHash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.Email,
		arg.Username,
		arg.Permission,
		arg.PasswordHash,
	)
	return err
}

const createWebAuthnSession = `-- name: CreateWebAuthnSession :exec
INSERT INTO webauthn_session(id, data)
VALUES ($1, $2)
`

type CreateWebAuthnSessionParams struct {
	ID   string               `json:"id"`
	Data webauthn.SessionData `json:"data"`
}

func (q *Queries) CreateWebAuthnSession(ctx context.Context, arg CreateWebAuthnSessionParams) error {
	_, err := q.db.Exec(ctx, createWebAuthnSession, arg.ID, arg.Data)
	return err
}

const deleteAppKey = `-- name: DeleteAppKey :exec
DELETE FROM appkey
WHERE id = $1
`

func (q *Queries) DeleteAppKey(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteAppKey, id)
	return err
}

const deleteFavorite = `-- name: DeleteFavorite :exec
DELETE FROM user_favorite
WHERE user_id = $1 AND image_id = $2
`

type DeleteFavoriteParams struct {
	UserID  int64 `json:"userId"`
	ImageID int64 `json:"imageId"`
}

func (q *Queries) DeleteFavorite(ctx context.Context, arg DeleteFavoriteParams) error {
	_, err := q.db.Exec(ctx, deleteFavorite, arg.UserID, arg.ImageID)
	return err
}

const deletePasskey = `-- name: DeletePasskey :exec
DELETE FROM webauthn_passkey
WHERE id = $1 AND user_id = $2
`

type DeletePasskeyParams struct {
	ID     []byte `json:"id"`
	UserID int64  `json:"userId"`
}

func (q *Queries) DeletePasskey(ctx context.Context, arg DeletePasskeyParams) error {
	_, err := q.db.Exec(ctx, deletePasskey, arg.ID, arg.UserID)
	return err
}

const filterImages = `-- name: FilterImages :many
WITH current_version AS (
  SELECT DISTINCT ON (image_id)
  id AS version_id, image_id, text, rating
  FROM public.version
  ORDER BY image_id, version_id DESC
),
include_tag_ids AS (
  SELECT id
  FROM tag
  WHERE tag.name = ANY ($4::TEXT[])
),
exclude_tag_ids AS (
  SELECT id
  FROM tag
  WHERE tag.name = ANY ($5::TEXT[])
)
SELECT i.id, i.image_url, i.image_key, i.created_at, cv.text, cv.rating, i.user_id, i.deleted_at
FROM image i
JOIN current_version cv ON cv.image_id = i.id

JOIN version_tag vt_in
  ON vt_in.version_id = cv.version_id
JOIN include_tag_ids it
  ON it.id = vt_in.tag_id
  
LEFT JOIN version_tag vt_ex
  ON vt_ex.version_id = cv.version_id
 AND vt_ex.tag_id IN (SELECT id FROM exclude_tag_ids)
WHERE cv.text LIKE CONCAT('%', $3, '%')
GROUP BY i.id, cv.version_id
HAVING
  COUNT(DISTINCT it.id) = (SELECT COUNT(*) FROM include_tag_ids)
  AND COUNT(vt_ex.tag_id) = 0
LIMIT $1
OFFSET $2
`

type FilterImagesParams struct {
	Limit       int32       `json:"limit"`
	Offset      int32       `json:"offset"`
	Text        interface{} `json:"text"`
	IncludeTags []string    `json:"includeTags"`
	ExcludeTags []string    `json:"excludeTags"`
}

type FilterImagesRow struct {
	ID        int64            `json:"id"`
	ImageUrl  string           `json:"imageUrl"`
	ImageKey  string           `json:"imageKey"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
	Text      string           `json:"text"`
	Rating    Rating           `json:"rating"`
	UserID    int64            `json:"userId"`
	DeletedAt pgtype.Timestamp `json:"deletedAt"`
}

// INCLUDE: must contain ALL include tags
// EXCLUDE: must contain NONE of exclude tags
func (q *Queries) FilterImages(ctx context.Context, arg FilterImagesParams) ([]FilterImagesRow, error) {
	rows, err := q.db.Query(ctx, filterImages,
		arg.Limit,
		arg.Offset,
		arg.Text,
		arg.IncludeTags,
		arg.ExcludeTags,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FilterImagesRow{}
	for rows.Next() {
		var i FilterImagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ImageUrl,
			&i.ImageKey,
			&i.CreatedAt,
			&i.Text,
			&i.Rating,
			&i.UserID,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAppKey = `-- name: GetAppKey :one
SELECT id, label, created_at, user_id, permission, last_activated_at, key FROM appkey
WHERE key = $1
`

func (q *Queries) GetAppKey(ctx context.Context, key string) (Appkey, error) {
	row := q.db.QueryRow(ctx, getAppKey, key)
	var i Appkey
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.CreatedAt,
		&i.UserID,
		&i.Permission,
		&i.LastActivatedAt,
		&i.Key,
	)
	return i, err
}

const getAppKeyById = `-- name: GetAppKeyById :one
SELECT id, label, created_at, user_id, permission, last_activated_at, key FROM appkey
WHERE id = $1
`

func (q *Queries) GetAppKeyById(ctx context.Context, id int64) (Appkey, error) {
	row := q.db.QueryRow(ctx, getAppKeyById, id)
	var i Appkey
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.CreatedAt,
		&i.UserID,
		&i.Permission,
		&i.LastActivatedAt,
		&i.Key,
	)
	return i, err
}

const getAppKeysByUser = `-- name: GetAppKeysByUser :many
SELECT id, created_at, label, user_id, permission, last_activated_at FROM appkey
WHERE user_id = $1
`

type GetAppKeysByUserRow struct {
	ID              int64            `json:"id"`
	CreatedAt       pgtype.Timestamp `json:"createdAt"`
	Label           string           `json:"label"`
	UserID          int64            `json:"userId"`
	Permission      int64            `json:"permission"`
	LastActivatedAt pgtype.Timestamp `json:"lastActivatedAt"`
}

func (q *Queries) GetAppKeysByUser(ctx context.Context, userID int64) ([]GetAppKeysByUserRow, error) {
	rows, err := q.db.Query(ctx, getAppKeysByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAppKeysByUserRow{}
	for rows.Next() {
		var i GetAppKeysByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Label,
			&i.UserID,
			&i.Permission,
			&i.LastActivatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCredentials = `-- name: GetCredentials :many
SELECT id, name, user_id, public_key, sign_count, transports, flags, created_at, aaguid FROM webauthn_passkey
WHERE user_id = $1
`

func (q *Queries) GetCredentials(ctx context.Context, userID int64) ([]WebauthnPasskey, error) {
	rows, err := q.db.Query(ctx, getCredentials, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebauthnPasskey{}
	for rows.Next() {
		var i WebauthnPasskey
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.UserID,
			&i.PublicKey,
			&i.SignCount,
			&i.Transports,
			&i.Flags,
			&i.CreatedAt,
			&i.Aaguid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFavoriteByShortcut = `-- name: GetFavoriteByShortcut :many
SELECT user_id, image_id, shortcut, favorited_at FROM user_favorite
WHERE shortcut LIKE $2 || '%'
  AND user_id = $1
`

type GetFavoriteByShortcutParams struct {
	UserID  int64       `json:"userId"`
	Keyword pgtype.Text `json:"keyword"`
}

func (q *Queries) GetFavoriteByShortcut(ctx context.Context, arg GetFavoriteByShortcutParams) ([]UserFavorite, error) {
	rows, err := q.db.Query(ctx, getFavoriteByShortcut, arg.UserID, arg.Keyword)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserFavorite{}
	for rows.Next() {
		var i UserFavorite
		if err := rows.Scan(
			&i.UserID,
			&i.ImageID,
			&i.Shortcut,
			&i.FavoritedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFavoriteImages = `-- name: GetFavoriteImages :many
WITH current_version AS (
  SELECT DISTINCT ON (image_id)
         id AS version_id,
         image_id,
         text, rating, version
  FROM version
  ORDER BY image_id, version DESC
)
SELECT fav.shortcut, fav.favorited_at, fav.user_id, i.id, i.image_key, i.image_url, cv.text, cv.rating, cv.version FROM user_favorite fav
JOIN image i ON fav.image_id = i.id
JOIN current_version cv ON i.current_version_id = cv.version_id
WHERE fav.user_id = $3
ORDER BY fav.favorited_at DESC, i.id
OFFSET $1
LIMIT $2
`

type GetFavoriteImagesParams struct {
	Offset int32 `json:"offset"`
	Limit  int32 `json:"limit"`
	UserID int64 `json:"userId"`
}

type GetFavoriteImagesRow struct {
	Shortcut    pgtype.Text      `json:"shortcut"`
	FavoritedAt pgtype.Timestamp `json:"favoritedAt"`
	UserID      int64            `json:"userId"`
	ID          int64            `json:"id"`
	ImageKey    string           `json:"imageKey"`
	ImageUrl    string           `json:"imageUrl"`
	Text        string           `json:"text"`
	Rating      Rating           `json:"rating"`
	Version     int32            `json:"version"`
}

func (q *Queries) GetFavoriteImages(ctx context.Context, arg GetFavoriteImagesParams) ([]GetFavoriteImagesRow, error) {
	rows, err := q.db.Query(ctx, getFavoriteImages, arg.Offset, arg.Limit, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFavoriteImagesRow{}
	for rows.Next() {
		var i GetFavoriteImagesRow
		if err := rows.Scan(
			&i.Shortcut,
			&i.FavoritedAt,
			&i.UserID,
			&i.ID,
			&i.ImageKey,
			&i.ImageUrl,
			&i.Text,
			&i.Rating,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFavoriteState = `-- name: GetFavoriteState :one

SELECT user_id, image_id, shortcut, favorited_at FROM user_favorite
WHERE user_id = $1 AND image_id = $2
`

type GetFavoriteStateParams struct {
	UserID  int64 `json:"userId"`
	ImageID int64 `json:"imageId"`
}

// ###################
// # Favorite
func (q *Queries) GetFavoriteState(ctx context.Context, arg GetFavoriteStateParams) (UserFavorite, error) {
	row := q.db.QueryRow(ctx, getFavoriteState, arg.UserID, arg.ImageID)
	var i UserFavorite
	err := row.Scan(
		&i.UserID,
		&i.ImageID,
		&i.Shortcut,
		&i.FavoritedAt,
	)
	return i, err
}

const getFavoriteTags = `-- name: GetFavoriteTags :many
WITH current_version AS (
  SELECT DISTINCT ON (v.image_id)
         v.id AS version_id,
         v.image_id
  FROM version v
  ORDER BY v.image_id, v.version DESC
),
favorite_versions AS (
  SELECT cv.version_id
  FROM user_favorite f
  JOIN current_version cv
    ON cv.image_id = f.image_id
  WHERE f.user_id = $1
)
SELECT DISTINCT t.id, t.name, COUNT(*) AS count
FROM favorite_versions fv
JOIN version_tag vt ON vt.version_id = fv.version_id
JOIN tag t ON t.id = vt.tag_id
GROUP BY t.id
ORDER BY count DESC
LIMIT $2
`

type GetFavoriteTagsParams struct {
	UserID int64 `json:"userId"`
	Limit  int32 `json:"limit"`
}

type GetFavoriteTagsRow struct {
	ID    int64  `json:"id"`
	Name  string `json:"name"`
	Count int64  `json:"count"`
}

func (q *Queries) GetFavoriteTags(ctx context.Context, arg GetFavoriteTagsParams) ([]GetFavoriteTagsRow, error) {
	rows, err := q.db.Query(ctx, getFavoriteTags, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFavoriteTagsRow{}
	for rows.Next() {
		var i GetFavoriteTagsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getImage = `-- name: GetImage :one
SELECT
    i.id, v.text, v.rating, image_url, image_key, i.created_at, 
    ui.id, ui.created_at, ui.username, i.current_version_id, v.version
FROM public.image i
JOIN public.user_identifier ui ON i.user_id = ui.id 
JOIN public.version v ON i.current_version_id = v.id
WHERE i.id = $1 AND i.deleted_at IS NULL LIMIT 1
`

type GetImageRow struct {
	ID               int64            `json:"id"`
	Text             string           `json:"text"`
	Rating           Rating           `json:"rating"`
	ImageUrl         string           `json:"imageUrl"`
	ImageKey         string           `json:"imageKey"`
	CreatedAt        pgtype.Timestamp `json:"createdAt"`
	UserIdentifier   UserIdentifier   `json:"userIdentifier"`
	CurrentVersionID pgtype.Int8      `json:"currentVersionId"`
	Version          int32            `json:"version"`
}

func (q *Queries) GetImage(ctx context.Context, id int64) (GetImageRow, error) {
	row := q.db.QueryRow(ctx, getImage, id)
	var i GetImageRow
	err := row.Scan(
		&i.ID,
		&i.Text,
		&i.Rating,
		&i.ImageUrl,
		&i.ImageKey,
		&i.CreatedAt,
		&i.UserIdentifier.ID,
		&i.UserIdentifier.CreatedAt,
		&i.UserIdentifier.Username,
		&i.CurrentVersionID,
		&i.Version,
	)
	return i, err
}

const getImageVersions = `-- name: GetImageVersions :many
SELECT v.id, v.created_at, v.image_id, v.version, v.text, v.rating, v.user_id, ui.id, ui.created_at, ui.username, ARRAY(
  SELECT name
  FROM tag t
  WHERE EXISTS (
    SELECT 1 FROM version_tag vt
    WHERE vt.version_id = v.id AND vt.tag_id = t.id
  )
)::TEXT[] AS tags
FROM public.version v
JOIN public.user_identifier ui ON v.user_id = ui.id
WHERE v.image_id = $1
ORDER BY v.created_at DESC
`

type GetImageVersionsRow struct {
	ID             int64            `json:"id"`
	CreatedAt      pgtype.Timestamp `json:"createdAt"`
	ImageID        int64            `json:"imageId"`
	Version        int32            `json:"version"`
	Text           string           `json:"text"`
	Rating         Rating           `json:"rating"`
	UserID         int64            `json:"userId"`
	UserIdentifier UserIdentifier   `json:"userIdentifier"`
	Tags           []string         `json:"tags"`
}

func (q *Queries) GetImageVersions(ctx context.Context, imageID int64) ([]GetImageVersionsRow, error) {
	rows, err := q.db.Query(ctx, getImageVersions, imageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetImageVersionsRow{}
	for rows.Next() {
		var i GetImageVersionsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.ImageID,
			&i.Version,
			&i.Text,
			&i.Rating,
			&i.UserID,
			&i.UserIdentifier.ID,
			&i.UserIdentifier.CreatedAt,
			&i.UserIdentifier.Username,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getImagesByUser = `-- name: GetImagesByUser :many
SELECT
    image.id, text, rating, image_url, image_key, current_version_id FROM image
JOIN version ON image.current_version_id = version.id
WHERE image.user_id = $1 AND image.deleted_at IS NULL
LIMIT $2 OFFSET $3
`

type GetImagesByUserParams struct {
	UserID int64 `json:"userId"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetImagesByUserRow struct {
	ID               int64       `json:"id"`
	Text             string      `json:"text"`
	Rating           Rating      `json:"rating"`
	ImageUrl         string      `json:"imageUrl"`
	ImageKey         string      `json:"imageKey"`
	CurrentVersionID pgtype.Int8 `json:"currentVersionId"`
}

func (q *Queries) GetImagesByUser(ctx context.Context, arg GetImagesByUserParams) ([]GetImagesByUserRow, error) {
	rows, err := q.db.Query(ctx, getImagesByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetImagesByUserRow{}
	for rows.Next() {
		var i GetImagesByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Text,
			&i.Rating,
			&i.ImageUrl,
			&i.ImageKey,
			&i.CurrentVersionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOther = `-- name: GetOther :one
SELECT id, created_at, username FROM public.user
WHERE id = $1
`

type GetOtherRow struct {
	ID        int64            `json:"id"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
	Username  string           `json:"username"`
}

func (q *Queries) GetOther(ctx context.Context, id int64) (GetOtherRow, error) {
	row := q.db.QueryRow(ctx, getOther, id)
	var i GetOtherRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.Username)
	return i, err
}

const getPasskey = `-- name: GetPasskey :many
SELECT id, name, user_id, aaguid, created_at FROM webauthn_passkey
WHERE user_id = $1
`

type GetPasskeyRow struct {
	ID        []byte           `json:"id"`
	Name      string           `json:"name"`
	UserID    int64            `json:"userId"`
	Aaguid    pgtype.UUID      `json:"aaguid"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
}

func (q *Queries) GetPasskey(ctx context.Context, userID int64) ([]GetPasskeyRow, error) {
	rows, err := q.db.Query(ctx, getPasskey, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPasskeyRow{}
	for rows.Next() {
		var i GetPasskeyRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.UserID,
			&i.Aaguid,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRandomImage = `-- name: GetRandomImage :many
WITH current_version AS (
  SELECT DISTINCT ON (image_id)
    id AS version_id, image_id, text, rating, version
  FROM version
  ORDER BY image_id, version DESC
)
SELECT i.id, i.image_url, i.image_key, cv.text, cv.rating
FROM current_version cv
JOIN image i ON cv.image_id = i.id
JOIN version_tag vt ON vt.version_id = cv.version_id
JOIN tag t ON t.id = vt.tag_id
WHERE t.name = $1
ORDER BY RANDOM()
LIMIT $2
`

type GetRandomImageParams struct {
	Name  string `json:"name"`
	Limit int32  `json:"limit"`
}

type GetRandomImageRow struct {
	ID       int64  `json:"id"`
	ImageUrl string `json:"imageUrl"`
	ImageKey string `json:"imageKey"`
	Text     string `json:"text"`
	Rating   Rating `json:"rating"`
}

func (q *Queries) GetRandomImage(ctx context.Context, arg GetRandomImageParams) ([]GetRandomImageRow, error) {
	rows, err := q.db.Query(ctx, getRandomImage, arg.Name, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRandomImageRow{}
	for rows.Next() {
		var i GetRandomImageRow
		if err := rows.Scan(
			&i.ID,
			&i.ImageUrl,
			&i.ImageKey,
			&i.Text,
			&i.Rating,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTagsByImage = `-- name: GetTagsByImage :many
WITH image_version AS (
    SELECT current_version_id AS version_id
    FROM image i
    WHERE i.id = $1
)
SELECT t.id, t.name FROM tag t
JOIN image_version iv ON EXISTS (
    SELECT 1 FROM version_tag vt
    WHERE vt.version_id = iv.version_id AND vt.tag_id = t.id
)
`

func (q *Queries) GetTagsByImage(ctx context.Context, id int64) ([]Tag, error) {
	rows, err := q.db.Query(ctx, getTagsByImage, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTagsByVersion = `-- name: GetTagsByVersion :many
SELECT tag.name FROM tag
INNER JOIN version_tag ON version_tag.tag_id = tag.id
WHERE tag.id = $1
`

func (q *Queries) GetTagsByVersion(ctx context.Context, id int64) ([]string, error) {
	rows, err := q.db.Query(ctx, getTagsByVersion, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTagsWithPrefix = `-- name: GetTagsWithPrefix :many
SELECT id, name FROM public.tag
WHERE name LIKE CONCAT($2::TEXT, '%')
ORDER BY name
LIMIT $1
`

type GetTagsWithPrefixParams struct {
	Limit  int32  `json:"limit"`
	Prefix string `json:"prefix"`
}

func (q *Queries) GetTagsWithPrefix(ctx context.Context, arg GetTagsWithPrefixParams) ([]Tag, error) {
	rows, err := q.db.Query(ctx, getTagsWithPrefix, arg.Limit, arg.Prefix)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUploadSession = `-- name: GetUploadSession :one
SELECT id, created_at, completed_at, user_id, key, status FROM public.upload_session
WHERE "id" = $1
`

func (q *Queries) GetUploadSession(ctx context.Context, id int64) (UploadSession, error) {
	row := q.db.QueryRow(ctx, getUploadSession, id)
	var i UploadSession
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.UserID,
		&i.Key,
		&i.Status,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, created_at, email, username, permission, password_hash, handle, preference FROM public.user
WHERE "id" = $1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Email,
		&i.Username,
		&i.Permission,
		&i.PasswordHash,
		&i.Handle,
		&i.Preference,
	)
	return i, err
}

const getUserByAppKey = `-- name: GetUserByAppKey :one

SELECT u.id, u.created_at, u.email, u.username, u.permission, u.password_hash, u.handle, u.preference, k.id AS key_id, k.permission AS key_permission FROM public.user u
INNER JOIN appkey k ON u.id = k.user_id
WHERE k.key = $1
`

type GetUserByAppKeyRow struct {
	ID            int64            `json:"id"`
	CreatedAt     pgtype.Timestamp `json:"createdAt"`
	Email         string           `json:"email"`
	Username      string           `json:"username"`
	Permission    int64            `json:"permission"`
	PasswordHash  []byte           `json:"passwordHash"`
	Handle        []byte           `json:"handle"`
	Preference    types.Preference `json:"preference"`
	KeyID         int64            `json:"keyId"`
	KeyPermission int64            `json:"keyPermission"`
}

// ###################
// # Integration
func (q *Queries) GetUserByAppKey(ctx context.Context, key string) (GetUserByAppKeyRow, error) {
	row := q.db.QueryRow(ctx, getUserByAppKey, key)
	var i GetUserByAppKeyRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Email,
		&i.Username,
		&i.Permission,
		&i.PasswordHash,
		&i.Handle,
		&i.Preference,
		&i.KeyID,
		&i.KeyPermission,
	)
	return i, err
}

const getUserByHandle = `-- name: GetUserByHandle :one
SELECT id, created_at, email, username, permission, password_hash, handle, preference FROM public.user
WHERE handle = $1
`

func (q *Queries) GetUserByHandle(ctx context.Context, handle []byte) (User, error) {
	row := q.db.QueryRow(ctx, getUserByHandle, handle)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Email,
		&i.Username,
		&i.Permission,
		&i.PasswordHash,
		&i.Handle,
		&i.Preference,
	)
	return i, err
}

const getUserByName = `-- name: GetUserByName :one
SELECT id, created_at, email, username, permission, password_hash, handle, preference FROM public.user
WHERE "username" = $1 LIMIT 1
`

func (q *Queries) GetUserByName(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByName, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Email,
		&i.Username,
		&i.Permission,
		&i.PasswordHash,
		&i.Handle,
		&i.Preference,
	)
	return i, err
}

const getUserContribution = `-- name: GetUserContribution :many
WITH image_daily AS (
  SELECT
    created_at::date AS day,
    COUNT(*) AS image_count
  FROM image
  WHERE image.user_id = $1
    AND created_at >= (CURRENT_DATE - INTERVAL '365 days')
  GROUP BY created_at::date
),

version_daily AS (
  SELECT
    created_at::date AS day,
    COUNT(*) AS version_count
  FROM version
  WHERE version.user_id = $1
    AND created_at >= (CURRENT_DATE - INTERVAL '365 days')
  GROUP BY created_at::date
)

SELECT
  COALESCE(i.day, v.day) AS day,
  COALESCE(i.image_count, 0)   AS image_count,
  COALESCE(v.version_count, 0) AS version_count
FROM image_daily i
FULL OUTER JOIN version_daily v
  ON v.day = i.day
ORDER BY i.day
`

type GetUserContributionRow struct {
	Day          pgtype.Date `json:"day"`
	ImageCount   int64       `json:"imageCount"`
	VersionCount int64       `json:"versionCount"`
}

func (q *Queries) GetUserContribution(ctx context.Context, userID int64) ([]GetUserContributionRow, error) {
	rows, err := q.db.Query(ctx, getUserContribution, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserContributionRow{}
	for rows.Next() {
		var i GetUserContributionRow
		if err := rows.Scan(&i.Day, &i.ImageCount, &i.VersionCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWebAuthnSession = `-- name: GetWebAuthnSession :one

SELECT id, created_at, data FROM webauthn_session
WHERE id = $1
`

// ###################
// # WebAuthn
func (q *Queries) GetWebAuthnSession(ctx context.Context, id string) (WebauthnSession, error) {
	row := q.db.QueryRow(ctx, getWebAuthnSession, id)
	var i WebauthnSession
	err := row.Scan(&i.ID, &i.CreatedAt, &i.Data)
	return i, err
}

const initializeVersion = `-- name: InitializeVersion :one
WITH new_version AS (
    INSERT INTO version(text, rating, image_id, user_id)
    VALUES ($1, $2, $3, $4)
    RETURNING id, image_id
), version_tags AS (
    INSERT INTO version_tag ("version_id", "tag_id")
    SELECT nv.id, t.id
    FROM new_version nv
    JOIN tag t ON t.name = ANY($5::TEXT[])
)
UPDATE image
SET current_version_id = new_version.id
FROM new_version
WHERE image.id = new_version.image_id
RETURNING image.id
`

type InitializeVersionParams struct {
	Text     string   `json:"text"`
	Rating   Rating   `json:"rating"`
	ImageID  int64    `json:"imageId"`
	UserID   int64    `json:"userId"`
	TagNames []string `json:"tagNames"`
}

func (q *Queries) InitializeVersion(ctx context.Context, arg InitializeVersionParams) (int64, error) {
	row := q.db.QueryRow(ctx, initializeVersion,
		arg.Text,
		arg.Rating,
		arg.ImageID,
		arg.UserID,
		arg.TagNames,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listImages = `-- name: ListImages :many
SELECT i.id, image_url, image_key, i.user_id, current_version_id, v.text, v.rating
FROM public.image i
JOIN public.version v ON i.current_version_id = v.id
ORDER BY i.created_at DESC
LIMIT $1 OFFSET $2
`

type ListImagesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListImagesRow struct {
	ID               int64       `json:"id"`
	ImageUrl         string      `json:"imageUrl"`
	ImageKey         string      `json:"imageKey"`
	UserID           int64       `json:"userId"`
	CurrentVersionID pgtype.Int8 `json:"currentVersionId"`
	Text             string      `json:"text"`
	Rating           Rating      `json:"rating"`
}

func (q *Queries) ListImages(ctx context.Context, arg ListImagesParams) ([]ListImagesRow, error) {
	rows, err := q.db.Query(ctx, listImages, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListImagesRow{}
	for rows.Next() {
		var i ListImagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ImageUrl,
			&i.ImageKey,
			&i.UserID,
			&i.CurrentVersionID,
			&i.Text,
			&i.Rating,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markUploadSessionAsExpired = `-- name: MarkUploadSessionAsExpired :exec
UPDATE public.upload_session
SET "status" = 'expired'
WHERE "id" = $1
`

func (q *Queries) MarkUploadSessionAsExpired(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markUploadSessionAsExpired, id)
	return err
}

const quickSearchFavorites = `-- name: QuickSearchFavorites :many
WITH current_version AS (
  SELECT DISTINCT ON (image_id)
         id AS version_id,
         image_id,
         text, rating
  FROM version
  ORDER BY image_id, version DESC
)
SELECT
  i.id, i.image_url, cv.text, cv.rating, 
  MAX(LENGTH(q.term))::FLOAT AS relevance
FROM image i
JOIN current_version cv ON cv.image_id = i.id
JOIN user_favorite fav ON fav.image_id = i.id
JOIN UNNEST($1::TEXT[]) AS q(term) ON fav.shortcut ILIKE q.term || '%'
WHERE fav.user_id = $2
GROUP BY i.id, i.image_url, cv.text, cv.rating
ORDER BY relevance DESC, i.id
LIMIT 12
`

type QuickSearchFavoritesParams struct {
	Keywords []string `json:"keywords"`
	UserID   int64    `json:"userId"`
}

type QuickSearchFavoritesRow struct {
	ID        int64   `json:"id"`
	ImageUrl  string  `json:"imageUrl"`
	Text      string  `json:"text"`
	Rating    Rating  `json:"rating"`
	Relevance float64 `json:"relevance"`
}

func (q *Queries) QuickSearchFavorites(ctx context.Context, arg QuickSearchFavoritesParams) ([]QuickSearchFavoritesRow, error) {
	rows, err := q.db.Query(ctx, quickSearchFavorites, arg.Keywords, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QuickSearchFavoritesRow{}
	for rows.Next() {
		var i QuickSearchFavoritesRow
		if err := rows.Scan(
			&i.ID,
			&i.ImageUrl,
			&i.Text,
			&i.Rating,
			&i.Relevance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const quickSearchImage = `-- name: QuickSearchImage :many
WITH current_version AS (
  SELECT DISTINCT ON (image_id)
         id AS version_id,
         image_id,
         text, rating
  FROM version
  ORDER BY image_id, version DESC
),

text_hits AS (
  SELECT
    cv.image_id,
    SUM(similarity(cv.text, q.term)) AS text_score
  FROM current_version cv,
       unnest($1::TEXT[]) AS q(term)
  WHERE cv.text LIKE '%' || q.term || '%'
  GROUP BY cv.image_id
),

tag_hits AS (
  SELECT
    cv.image_id, COUNT(*) * 0.5 AS tag_score
  FROM current_version cv
  JOIN version_tag vt
    ON vt.version_id = cv.version_id
  JOIN tag t
    ON t.id = vt.tag_id
  WHERE t.name = ANY ($1::TEXT[])
  GROUP BY cv.image_id
)

SELECT
  i.id, i.image_url, cv.text, cv.rating, 
  (COALESCE(th.text_score, 0.0) + COALESCE(tg.tag_score, 0.0))::FLOAT AS relevance
FROM image i
JOIN current_version cv ON cv.image_id = i.id
LEFT JOIN text_hits th ON th.image_id = i.id
LEFT JOIN tag_hits tg ON tg.image_id = i.id
WHERE
  th.image_id IS NOT NULL
  OR tg.image_id IS NOT NULL
ORDER BY relevance DESC, i.id
LIMIT 12
`

type QuickSearchImageRow struct {
	ID        int64   `json:"id"`
	ImageUrl  string  `json:"imageUrl"`
	Text      string  `json:"text"`
	Rating    Rating  `json:"rating"`
	Relevance float64 `json:"relevance"`
}

func (q *Queries) QuickSearchImage(ctx context.Context, keywords []string) ([]QuickSearchImageRow, error) {
	rows, err := q.db.Query(ctx, quickSearchImage, keywords)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QuickSearchImageRow{}
	for rows.Next() {
		var i QuickSearchImageRow
		if err := rows.Scan(
			&i.ID,
			&i.ImageUrl,
			&i.Text,
			&i.Rating,
			&i.Relevance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setFavoriteShortcut = `-- name: SetFavoriteShortcut :exec
UPDATE user_favorite
SET shortcut = $3
WHERE user_id = $1 AND image_id = $2
`

type SetFavoriteShortcutParams struct {
	UserID   int64       `json:"userId"`
	ImageID  int64       `json:"imageId"`
	Shortcut pgtype.Text `json:"shortcut"`
}

func (q *Queries) SetFavoriteShortcut(ctx context.Context, arg SetFavoriteShortcutParams) error {
	_, err := q.db.Exec(ctx, setFavoriteShortcut, arg.UserID, arg.ImageID, arg.Shortcut)
	return err
}

const setImageEmbedding = `-- name: SetImageEmbedding :exec
UPDATE image SET embedding = $2::vector WHERE id = $1
`

type SetImageEmbeddingParams struct {
	ID      int64           `json:"id"`
	Column2 pgvector.Vector `json:"column2"`
}

func (q *Queries) SetImageEmbedding(ctx context.Context, arg SetImageEmbeddingParams) error {
	_, err := q.db.Exec(ctx, setImageEmbedding, arg.ID, arg.Column2)
	return err
}

const setImageHash = `-- name: SetImageHash :exec
UPDATE image SET "image_hash" = $2 WHERE "id" = $1
`

type SetImageHashParams struct {
	ID        int64       `json:"id"`
	ImageHash pgtype.Text `json:"imageHash"`
}

func (q *Queries) SetImageHash(ctx context.Context, arg SetImageHashParams) error {
	_, err := q.db.Exec(ctx, setImageHash, arg.ID, arg.ImageHash)
	return err
}

const setImageVersion = `-- name: SetImageVersion :exec
UPDATE image SET "current_version_id" = $2 WHERE "id" = $1
`

type SetImageVersionParams struct {
	ID               int64       `json:"id"`
	CurrentVersionID pgtype.Int8 `json:"currentVersionId"`
}

func (q *Queries) SetImageVersion(ctx context.Context, arg SetImageVersionParams) error {
	_, err := q.db.Exec(ctx, setImageVersion, arg.ID, arg.CurrentVersionID)
	return err
}

const setPasskeyName = `-- name: SetPasskeyName :exec
UPDATE webauthn_passkey
SET name = $1
WHERE id = $2 AND user_id = $3
`

type SetPasskeyNameParams struct {
	Name   string `json:"name"`
	ID     []byte `json:"id"`
	UserID int64  `json:"userId"`
}

func (q *Queries) SetPasskeyName(ctx context.Context, arg SetPasskeyNameParams) error {
	_, err := q.db.Exec(ctx, setPasskeyName, arg.Name, arg.ID, arg.UserID)
	return err
}

const setUserPermission = `-- name: SetUserPermission :exec
UPDATE public.user SET "permission" = $2 WHERE "id" = $1
`

type SetUserPermissionParams struct {
	ID         int64 `json:"id"`
	Permission int64 `json:"permission"`
}

func (q *Queries) SetUserPermission(ctx context.Context, arg SetUserPermissionParams) error {
	_, err := q.db.Exec(ctx, setUserPermission, arg.ID, arg.Permission)
	return err
}

const setUserPreference = `-- name: SetUserPreference :exec
UPDATE public.user
SET "preference" = $2
WHERE "id" = $1
`

type SetUserPreferenceParams struct {
	ID         int64            `json:"id"`
	Preference types.Preference `json:"preference"`
}

func (q *Queries) SetUserPreference(ctx context.Context, arg SetUserPreferenceParams) error {
	_, err := q.db.Exec(ctx, setUserPreference, arg.ID, arg.Preference)
	return err
}

const setVersionRating = `-- name: SetVersionRating :exec
UPDATE version SET "rating" = $2 WHERE "id" = $1
`

type SetVersionRatingParams struct {
	ID     int64  `json:"id"`
	Rating Rating `json:"rating"`
}

func (q *Queries) SetVersionRating(ctx context.Context, arg SetVersionRatingParams) error {
	_, err := q.db.Exec(ctx, setVersionRating, arg.ID, arg.Rating)
	return err
}

const setVersionText = `-- name: SetVersionText :exec
UPDATE version SET "text" = $2 WHERE "id" = $1
`

type SetVersionTextParams struct {
	ID   int64  `json:"id"`
	Text string `json:"text"`
}

func (q *Queries) SetVersionText(ctx context.Context, arg SetVersionTextParams) error {
	_, err := q.db.Exec(ctx, setVersionText, arg.ID, arg.Text)
	return err
}

const updateAppKey = `-- name: UpdateAppKey :exec
UPDATE appkey
SET permission = $1, label = $2
WHERE id = $3
`

type UpdateAppKeyParams struct {
	Permission int64  `json:"permission"`
	Label      string `json:"label"`
	ID         int64  `json:"id"`
}

func (q *Queries) UpdateAppKey(ctx context.Context, arg UpdateAppKeyParams) error {
	_, err := q.db.Exec(ctx, updateAppKey, arg.Permission, arg.Label, arg.ID)
	return err
}

const updateAppKeyUsedDate = `-- name: UpdateAppKeyUsedDate :exec
UPDATE appkey
SET last_activated_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateAppKeyUsedDate(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, updateAppKeyUsedDate, id)
	return err
}
